import type { AboutSlug } from "./data";

export interface AboutContent {
  slug: AboutSlug;
  title: string;
  kicker: string;
  intro: string;
  paragraphs: (string | { quote: string } | { heading: string } | { image: string; alt?: string })[];
  closing?: string;
}

export const ABOUT_CONTENT: Record<AboutSlug, AboutContent> = {
  faith: {
    slug: "faith",
    title: "The Story of How I Met Christ",
    kicker: "Faith",
    intro: "Truth cannot remain hidden forever.",
    paragraphs: [
      "For a long time now, I have felt a strong conviction to document my journey with God. The burden has only grown stronger with time. I believe that years from now—perhaps even decades from now—someone may come across these writings and be encouraged by what the Lord has done in my life.",
      "My name is Emmanuel. Above every other title I could ever have, I am a child of God and a lover of Jesus Christ. That is the greatest description of who I am.",
      "No matter what I go through, there is always a deep sense of rest that comes whenever the Holy Spirit reminds me of how my life will end—not in regret, but in the fulfillment of God's purpose. Sometimes that thought overwhelms me because I cannot fully comprehend the plans God has for my life. Yet, while I am still in the process of becoming all He has called me to be, I believe obeying the Holy Spirit by writing this testimony is the right thing to do.",
      "Like every believer, I was once a slave to sin. My life was filled with darkness, emptiness, and spiritual blindness. From a very young age, I was exposed to many immoral things. Although my parents were disciplined people who raised me with good morals, there were many things I kept hidden from them.",
      "While I was in Primary Three in 2015, I became involved in a sexual misconduct incident at school. Although it was not actual sexual intercourse, it was serious enough to lead to my suspension. The situation even escalated to a police case. The girl's parents accused my mother, who was a teacher in the same school, alongside my class teacher and the school management. Looking back now, we were both children who had acted wrongly, yet the incident left me carrying deep shame. I felt like the worst son, student, brother, and family member anyone could ever have.",
      "I am not proud of sharing these details, but I have come to understand that what remains hidden in darkness continues to weigh heavily on the heart. I no longer want to hide the person I used to be because the grace of God is best seen against the backdrop of the life He rescued me from.",
      "From that period until I graduated from secondary school in 2024, my life was marked by repeated struggles with sin. I did not truly know God, and apart from Him, a life of sin is all anyone can naturally live.",
      "During my SS3 days, I became involved in another immoral act that was secretly recorded by someone. Afterward, the person threatened me with the video and repeatedly promised to expose me publicly. I lived in fear and anxiety. Truly, a life without Christ is a life in crisis. Unknown to me, while I was drowning in guilt and fear, God was quietly arranging every detail of my life. He was drawing the lines, connecting the dots, and preparing the path that would eventually lead me to Himself.",
      "After graduating from secondary school, I left Ogun State, where I had lived with my family, and travelled to Osun State to work while waiting for university admission. I worked at the residence of a respected Christian businessman. Although many people referred to him as a politician because of his associations, those who knew him closely testified that he refused to participate in corruption and remained committed to his Christian convictions.",
      "When I arrived, I was given a two-bedroom bungalow all to myself. For the first time in my life, I lived completely alone.",
      "Everything felt different.",
      "There was no brother to play games with or sister to talk to. Gradually, my phone became my closest companion. I buried myself in it, believing it could fill the emptiness within me. I even ventured into content creation, hoping that constant activity would satisfy me. Yet none of those things could fill the void inside my soul.",
      "Then came the night that changed my life forever.",
      "I often tell people that I gave my life to Christ on August 25, 2024, because for a long time I could not remember the exact date. However, after about a year, I carefully searched through my phone gallery and realized it actually happened during the early days of September. Regardless of the exact date, that season remains my spiritual birthday—a day I will always celebrate and use to encourage others to receive Jesus Christ.",
      "That night, I attended a Methodist campus fellowship vigil. To everyone else, it may have seemed like another ordinary meeting, but heaven had arranged it for my salvation. God had prepared that gathering long before I arrived.",
      "When the service ended and I returned home the following morning, something had changed inside me.",
      "I suddenly desired to worship God.",
      "I desired to pray.",
      "I longed for His presence.",
      "I cannot remember the exact words I prayed that night or whether I formally confessed Jesus with my mouth, but I know this: my heart had found its Father. I began singing songs that declared God as my Father, and from that day forward, my hunger for Him only continued to grow. The more I prayed, the more I wanted to pray. The more I worshipped, the more I desired His presence. It was as though the missing piece of my life had finally been found.",
      "Loneliness became an advantage because I was no longer truly alone. I had become conscious of God's presence.",
      "Not long afterward, I began reaching out to my former secondary school classmates to tell them about the love of Christ I had experienced.",
      "We started holding online night meetings where we studied the Scriptures together. Since many of us were waiting for university admission, I encouraged everyone to trust God completely. We named the group \"IN GOD WE TRUST.\"",
      "Looking back today, I can confidently say that this was the beginning of the ministry God was entrusting to me.",
      "The Lord then began taking me through a season of intense training.",
      "Those days prepared me for the days that would follow.",
      "He taught me sacrifice.",
      "He taught me perseverance.",
      "He taught me love for His Church.",
      "There were nights when I would schedule a meeting for over thirty people, yet only two people would join. At times it was discouraging, but God was teaching me that ministry is never measured by numbers but by faithfulness.",
      "In November 2024, I gained admission into the University of Benin to study Geomatics Engineering.",
      "I arrived on campus with the same burning passion for Christ.",
      "I became a member of the Anglican Students' Fellowship (ASF) and was accommodated in Hall Four. University life exposed me to a level of worldliness I had never experienced before. I encountered many people who did not know Christ, and my heart became burdened for them.",
      "I devoted myself to prayer, fasting, Bible study, and evangelism. At the same time, I remained committed to leading the WhatsApp fellowship. My hunger to know God continued to grow.",
      "Everything seemed perfect.",
      "But there was still a battle within me.",
      "Although I had received salvation, God immediately began the lifelong work of sanctification in my heart.",
      "The Holy Spirit started changing my desires. The sins I once practiced without conviction now deeply grieved me. Whenever I fell, I ran back to God in repentance and depended on His mercy to help me stand again.",
      "One of my greatest struggles before knowing Christ had been pornography and masturbation. Even after I became born again, I found myself fighting against those old habits. I hated them with everything inside me because I knew they no longer reflected the person God had called me to be.",
      "Again and again, I cried out to God for freedom.",
      "Slowly but surely, He delivered me.",
      "I cannot point to the exact day the addiction was broken, but one day I simply realized that I was no longer bound by it.",
      { quote: "Therefore, if anyone is in Christ, he is a new creation. Old things have passed away; behold, all things have become new." },
      "As time passed, my walk with God became even more serious.",
      "During my first-year second semester, I became deeply devoted to night prayers and intercession. I created another WhatsApp prayer group and invited people from TikTok who were hungry for God. Soon, nearly seventy people from different parts of Africa were praying and studying God's Word together every night.",
      "God was gradually drawing my heart toward the ministry of intercession.",
      "Not long afterward, I was nominated and officially appointed as the Anglican Intercessory Ministry (A.I.M.) Leader in the Anglican Students' Fellowship.",
      "Our fellowship is blessed with spiritually discerning leaders who sincerely seek the direction of the Holy Spirit before making decisions. Although many of them had never witnessed my private prayer life, the Lord made His will known.",
      "With that appointment came far more than an office or a title.",
      "God entrusted me with greater spiritual responsibility.",
      "He began to increase His grace upon my life, deepened my discernment, strengthened my burden for souls, and taught me what it truly means to stand in the place of prayer for others.",
      "And as I write these words today, I know that this is only the beginning.",
      "The same God who found me in my darkness is still writing my story.",
    ],
    closing: "(Last updated: 14th May, 2026)\nTo Him alone be all the glory.",
  },
  cybersecurity: {
    slug: "cybersecurity",
    title: "Cybersecurity",
    kicker: "Cybersecurity",
    intro: "Cybersecurity is more than a profession to me—it is a calling to protect, serve, and solve problems.",
    paragraphs: [
      "In a world where technology has become an essential part of everyday life, safeguarding digital systems and information has never been more important.",
      "My interest in cybersecurity began with a deep curiosity about computers and how they work. That curiosity gradually developed into a passion for understanding how systems can be secured against cyber threats and how technology can be used responsibly to improve lives.",
      "As I continue to grow academically and professionally, I remain committed to learning new technologies, strengthening my technical skills, and developing the mindset required of an effective cybersecurity professional. I believe that excellence is built through consistency, discipline, and a willingness to keep learning.",
      "For me, cybersecurity is not simply about defending networks—it is about protecting people, preserving trust, and using knowledge to make a meaningful difference in society.",
      { heading: "Why I Hate Cybercrime: Defending a Different Kind of Frontline" },
      { image: "cybercrime-overview", alt: "An overview of cyber crime — phishing, brute force, malware, DDoS, MITM, keylogging, cryptojacking" },
      "Growing up, my dream was clear: I wanted to be a military man. I envisioned myself on the frontlines, standing between innocent people and those who wished them harm. I wanted to face the \"bad guys\" head-on. However, life often has different plans. My mother, with a heart full of love and worry, couldn't bear the thought of my life becoming a game of bullets and luck. Out of respect for her, I stepped back from that path.",
      "But the fire to protect didn't go out; it just changed its fuel. I soon realized that the most dangerous \"bad guys\" today aren't always carrying rifles—they're carrying keyboards. I found that I could still be a soldier, not on land, but in the cyber space.",
      { heading: "The Invisible Enemy" },
      "I hate cybercrime because it is a cowardly form of warfare. It attacks people in their homes, drains their life savings, and exploits their trust without ever showing a face. Whether it's phishing, malware, or cryptojacking, these aren't just technical glitches—they are direct attacks on people's livelihoods and peace of mind.",
      { heading: "My New Battlefield" },
      "I may not be wearing a uniform or carrying a weapon, but every time I study a Brute Force Attack or learn to prevent a Man-in-the-Middle exploit, I am training for combat. My \"bullets\" are lines of code, and my \"armor\" is 2FA and encryption.",
      "The goal remains the same: to stand in the gap, to outsmart the predator, and to ensure that the digital world stays safe for everyone. The theater of war has changed, but the mission hasn't.",
    ],
  },
  leadership: {
    slug: "leadership",
    title: "Leadership",
    kicker: "Leadership",
    intro: "I lead by serving — building people up, communicating clearly, and modeling integrity in every room.",
    paragraphs: [
      "Leadership, to me, is not about position or title. It is about the responsibility of stewardship — being trusted with people, vision, and influence, and using all three to lift others rather than yourself.",
      "From leading the \"IN GOD WE TRUST\" WhatsApp fellowship before university, to serving as the Anglican Intercessory Ministry (A.I.M.) Leader at the University of Benin, the Lord has consistently taught me that ministry and leadership are measured by faithfulness, not numbers.",
      "I am learning that great leaders are first great servants. They listen more than they speak, they model before they instruct, and they pray for the people they lead before they correct them.",
      "My desire is to become a leader the body of Christ can trust — clear in vision, consistent in character, and compassionate in approach. Leadership is the long, quiet work of becoming worthy of the people God places in your care.",
    ],
  },
  education: {
    slug: "education",
    title: "Education",
    kicker: "Education",
    intro: "Education is one of the greatest investments anyone can make.",
    paragraphs: [
      "It equips the mind, develops critical thinking, and prepares individuals to contribute meaningfully to society.",
      "I am currently studying Geomatics Engineering at the University of Benin while continually expanding my knowledge in technology, cybersecurity, leadership, and personal development. Beyond the classroom, I believe learning should never stop. Books, online courses, mentorship, practical experience, and everyday life all provide valuable opportunities for growth.",
      "My goal is not merely to earn certificates but to acquire knowledge that can solve real-world problems, create value, and positively impact others.",
      "I believe that education, when combined with integrity, discipline, and a heart for service, becomes a powerful tool for transformation.",
    ],
  },
  "personal-growth": {
    slug: "personal-growth",
    title: "Personal Growth",
    kicker: "Personal Growth",
    intro: "Personal growth is a lifelong journey of becoming the person God created me to be.",
    paragraphs: [
      "It involves intentional improvement in character, knowledge, discipline, relationships, and purpose.",
      "I believe growth happens when we embrace learning, welcome correction, remain teachable, and consistently challenge ourselves to become better than we were yesterday. Every experience—whether success, failure, joy, or disappointment—contains lessons that shape us.",
      "For me, personal growth includes developing spiritual maturity, strengthening emotional intelligence, improving communication, building healthy habits, and pursuing excellence in every area of life.",
      "I do not aim for perfection; I aim for progress. My desire is to continue growing into a man of integrity, wisdom, competence, and compassion, living a life that reflects both excellence and purpose.",
      "These pages are a reflection of that ongoing journey, and I hope that as I grow, they will continue to grow with me.",
    ],
  },
};