/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutTopicRouteImport } from './routes/about.$topic'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTopicRoute = AboutTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/journey': typeof JourneyRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/about/$topic': typeof AboutTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/journey': typeof JourneyRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/about/$topic': typeof AboutTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/journey': typeof JourneyRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/about/$topic': typeof AboutTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/journey'
    | '/projects'
    | '/sitemap.xml'
    | '/skills'
    | '/about/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/journey'
    | '/projects'
    | '/sitemap.xml'
    | '/skills'
    | '/about/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/journey'
    | '/projects'
    | '/sitemap.xml'
    | '/skills'
    | '/about/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$topic': {
      id: '/about/$topic'
      path: '/$topic'
      fullPath: '/about/$topic'
      preLoaderRoute: typeof AboutTopicRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutTopicRoute: typeof AboutTopicRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutTopicRoute: AboutTopicRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  JourneyRoute: JourneyRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
